### ISSUE TITLE
Not sure about the flow here

### ISSUE THREAD

**Issue by JMRedford** [bennjon/chu_shogi#5]
https://github.com/bennjon/chu_shogi/blob/7e81fbb4b7bfbbc3ad4b3ef312635263355f6749/game.py#L122

I'm not sure if it's a great idea to re-generate the valid moves for every piece on the board every time a piece is selected

**Comment by JMRedford** [comment]
I'm thinking that we need to collect two different clicks.  The first to select which piece is to be moved, the second to choose which space to move to.  With a boolean flag set after the first click to inform wether this is an initial lion's move.  Perhaps we should have a state variable to keep track of what phase of the game we are in, wether we are selecting a piece, selecting a move, or waiting on the opponent to send a move.  I'll work on that tonight.

**Comment by JMRedford** [comment]
Another idea about flow:  I think we should construct the string to send to the server separately and before resolving the move.  That way we can pass the string to a function to resolve moves both from the local and remote player and not have to do the same thing two different ways.

**Comment by JMRedford** [comment]
Oh, and it is actually not an illegal move in chu to put yourself in check... it's just a losing move (unless you have a crown prince).  Which simplifies things somewhat.

**Comment by bennjon** [comment]
> [chu_shogi/game.py](https://github.com/bennjon/chu_shogi/blob/7e81fbb4b7bfbbc3ad4b3ef312635263355f6749/game.py#L122)
> 
> Line 122 in [7e81fbb](/bennjon/chu_shogi/commit/7e81fbb4b7bfbbc3ad4b3ef312635263355f6749)
> 
>  bo.update_moves() 
> I'm not sure if it's a great idea to re-generate the valid moves for every piece on the board every time a piece is selected

I agree with this. In fact I was hesitant to put it in this form in the last merge. Im glad you confirmed my suspicion. This will be my next refactor.

**Comment by bennjon** [comment]
> Oh, and it is actually not an illegal move in chu to put yourself in check... it's just a losing move (unless you have a crown prince). Which simplifies things somewhat.

Good call on this. I will update the valid moves.

**Comment by JMRedford** [comment]
Actually, I've refactored quite a bit on the dev-4 branch if you want to give it a look.
